apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    role: app
spec:
  replicas: 3
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: app
        image: "{{ image_id }}"
        volumes:
           - /var/lib/jenkins/workspace/.kube:/var/lib/jenkins/workspace/.kube
        resources:
          requests:
            cpu: 10m
