apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    role: app
spec:
  automountServiceAccountToken: false
  replicas: 3
  selector:
    matchLabels:
      role: app
  env:
  - name: KUBERNETES_SERVICE_HOST
    value: "192.168.1.96"
  - name: KUBERNETES_SERVICE_PORT
    value: "6443"

  template:
    metadata:
      labels:
        role: app
    spec:
      volumes:
      - name: kube-config
        configMap:
           name: kube-config
           items:
           - key: config
             path: config
      containers:
      - name: app
        image: "{{ image_id }}"
        resources:
          requests:
            cpu: 10m
        volumeMounts:
        - name: kube-config
          mountPath: /var/lib/jenkins/.kube/config
          subPath: config
