apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    role: app
spec:
  replicas: 3
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      volumes:
      - name: kube-config
        configMap:
           name: kube-config
           items:
           - key: config
             path: config
      containers:
      - name: app
        image: "{{ image_id }}"
        env:
          - name: "KUBERNETES_SERVICE_HOST"
            value: "10.101.174.127"
          - name: "KUBERNETES_SERVICE_PORT"
            value: "30000"
        resources:
          requests:
            cpu: 10m
      volumeMounts:
      - name: kube-config
        mountPath: /var/lib/jenkins/.kube/config
        subPath: config

      
