apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    role: app
spec:
  replicas: 3
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      volumes:
      - name: kube-config
        mountPath: /var/lib/jenkins/.kube
      containers:
      - name: app
        image: "{{ image_id }}"
        resources:
          requests:
            cpu: 10m
        volumeMounts:
        - name: kube-config
          hostPath: /var/lib/jenkins/.kube/
            subPath: config
           
      
